#!/usr/bin/env bash

dir="$HOME/.config/rofi/launchers/type-2"
theme='web-search'

# Prompt for input
query=$(rofi \
    -dmenu \
    -theme "${dir}/${theme}".rasi \
    -p "🔍 Search web: ")

# Only proceed if the query isn't empty
if [ -n "$query" ]; then
    # Encode the query for a URL
    encoded_query=$(printf '%s\n' "$query" | jq -sRr @uri)
 
    # Choose your preferred search engine
    brave "https://duckduckgo.com/?q=$encoded_query" &
    hyprctl dispatch 'workspace 1' &
fi

