
[font]
size = 12.75
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }

[env]
TERM = "screen-256color"

[window]
opacity = 0.98
padding = { x  = 0, y = 1 }

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
